In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv('male_players.csv')
test = pd.read_csv('players_22.csv')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12224\134610228.py:1: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv('male_players.csv')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12224\134610228.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  test = pd.read_csv('players_22.csv')

In [4]:
train

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/150002,15,2,2014-09-18,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,...,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png
1,20801,/player/20801/c-ronaldo-dos-santos-aveiro/150002,15,2,2014-09-18,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,...,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png
2,9014,/player/9014/arjen-robben/150002,15,2,2014-09-18,A. Robben,Arjen Robben,"RM, LM, RW",90,90,...,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png
3,41236,/player/41236/zlatan-ibrahimovic/150002,15,2,2014-09-18,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,...,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png
4,167495,/player/167495/manuel-neuer/150002,15,2,2014-09-18,M. Neuer,Manuel Peter Neuer,GK,90,90,...,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,269011,/player/269011/ziye-zhao/230002,23,2,2022-09-26,Zhao Ziye,赵梓业,RW,46,61,...,32+2,32+2,37+2,36+2,31+2,31+2,31+2,36+2,14+2,https://cdn.sofifa.net/players/269/011/23_120.png
161579,269019,/player/269019/junjie-wu/230002,23,2,2022-09-26,Wu Junjie,吴俊杰,LB,46,58,...,41+2,41+2,43+2,44+2,48+2,48+2,48+2,44+2,15+2,https://cdn.sofifa.net/players/269/019/23_120.png
161580,271093,/player/271093/kailin-barlow/230002,23,2,2022-09-26,K. Barlow,Kailin Barlow,CDM,46,58,...,45+2,45+2,47+2,47+2,46+2,46+2,46+2,47+2,14+2,https://cdn.sofifa.net/players/271/093/23_120.png
161581,271555,/player/271555/gideon-tetteh/230002,23,2,2022-09-26,G. Tetteh,Gideon Tetteh,"RW, LW",46,70,...,30+2,30+2,34+2,32+2,28+2,28+2,28+2,32+2,15+2,https://cdn.sofifa.net/players/271/555/23_120.png
161582,271608,/player/271608/aqeel-al-dhafeeri/230002,23,2,2022-09-26,A. Al Dhafeeri,Aqeel Al Dhafeeri,CB,46,63,...,40+2,40+2,39+2,41+2,46+2,46+2,46+2,41+2,13+2,https://cdn.sofifa.net/players/271/608/23_120.png

In [5]:
train.columns.tolist()

['player_id',
 'player_url',
 'fifa_version',
 'fifa_update',
 'fifa_update_date',
 'short_name',
 'long_name',
 'player_positions',
 'overall',
 'potential',
 'value_eur',
 'wage_eur',
 'age',
 'dob',
 'height_cm',
 'weight_kg',
 'league_id',
 'league_name',
 'league_level',
 'club_team_id',
 'club_name',
 'club_position',
 'club_jersey_number',
 'club_loaned_from',
 'club_joined_date',
 'club_contract_valid_until_year',
 'nationality_id',
 'nationality_name',
 'nation_team_id',
 'nation_position',
 'nation_jersey_number',
 'preferred_foot',
 'weak_foot',
 'skill_moves',
 'international_reputation',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'player_tags',
 'player_traits',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking_awareness',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'goalkeeping_speed',
 'ls',
 'st',
 'rs',
 'lw',
 'lf',
 'cf',
 'rf',
 'rw',
 'lam',
 'cam',
 'ram',
 'lm',
 'lcm',
 'cm',
 'rcm',
 'rm',
 'lwb',
 'ldm',
 'cdm',
 'rdm',
 'rwb',
 'lb',
 'lcb',
 'cb',
 'rcb',
 'rb',
 'gk',
 'player_face_url']

In [6]:
train_main = train.drop(columns = ['player_id','player_url','fifa_version','fifa_update','fifa_update_date','short_name','long_name','club_joined_date','dob','player_face_url'],inplace=False)

In [7]:
train_main.head()

,player_positions,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_id,league_name,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,CF,93,95,100500000.0,550000.0,27,169,67,53.0,La Liga,...,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3
1,"LW, LM",92,92,79000000.0,375000.0,29,185,80,53.0,La Liga,...,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3
2,"RM, LM, RW",90,90,54500000.0,275000.0,30,180,80,19.0,Bundesliga,...,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3
3,ST,90,90,52500000.0,275000.0,32,195,95,16.0,Ligue 1,...,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3
4,GK,90,90,63500000.0,300000.0,28,193,92,19.0,Bundesliga,...,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3

Dropping Columns With More than 30% missing values

In [8]:
threshold = 0.3 * len(train_main)

# Identify columns to drop
columns_to_drop = []
for col in train_main.columns:
    if train_main[col].isna().sum() > threshold:
        columns_to_drop.append(col)

# Drop the columns
train_main.drop(columns=columns_to_drop, inplace=True)

new_main = train_main

In [9]:
new_main.columns

Index(['player_positions', 'overall', 'potential', 'value_eur', 'wage_eur',
       'age', 'height_cm', 'weight_kg', 'league_id', 'league_name',
       'league_level', 'club_team_id', 'club_name', 'club_position',
       'club_jersey_number', 'club_contract_valid_until_year',
       'nationality_id', 'nationality_name', 'preferred_foot', 'weak_foot',
       'skill_moves', 'international_reputation', 'work_rate', 'body_type',
       'real_face', 'pace', 'shooting', 'passing', 'dribbling', 'defending',
       'physic', 'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',
       'movement_reactions', 'movement_balance', 'power_shot_power',
       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',
       'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_marking_awareness',
       'defending_standing_tackle', 'defending_sliding_tackle',
       'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes', 'ls', 'st', 'rs',
       'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm',
       'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb',
       'rcb', 'rb', 'gk'],
      dtype='object')

In [10]:
numeric_data=new_main.select_dtypes(include=np.number)
non_numeric=new_main.select_dtypes(include = ['object'])

In [11]:
numeric_data

,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_id,league_level,club_team_id,...,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,93,95,100500000.0,550000.0,27,169,67,53.0,1.0,241.0,...,76,NaN,25,21,20,6,11,15,14,8
1,92,92,79000000.0,375000.0,29,185,80,53.0,1.0,243.0,...,85,NaN,22,31,23,7,11,15,14,11
2,90,90,54500000.0,275000.0,30,180,80,19.0,1.0,21.0,...,80,NaN,29,26,26,10,8,11,5,15
3,90,90,52500000.0,275000.0,32,195,95,16.0,1.0,73.0,...,91,NaN,25,41,27,13,15,10,9,12
4,90,90,63500000.0,300000.0,28,193,92,19.0,1.0,21.0,...,37,NaN,25,25,25,87,85,92,90,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46,61,110000.0,700.0,18,180,73,2012.0,1.0,112978.0,...,54,40.0,23,21,25,9,13,13,12,7
161579,46,58,110000.0,750.0,19,188,83,2012.0,1.0,112429.0,...,31,35.0,50,51,45,6,14,8,13,14
161580,46,58,110000.0,500.0,19,181,73,65.0,1.0,563.0,...,37,35.0,36,45,50,8,9,7,14,9
161581,46,70,150000.0,500.0,17,175,68,65.0,1.0,306.0,...,63,43.0,19,17,14,13,12,14,7,13
161582,46,63,110000.0,500.0,17,180,70,350.0,1.0,112990.0,...,25,30.0,50,45,42,13,7,6,6,14

Filling missing values

In [12]:
number_impt= numeric_data.fillna(numeric_data.mean())

In [13]:
number_impt

,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_id,league_level,club_team_id,...,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,93,95,100500000.0,550000.0,27,169,67,53.0,1.0,241.0,...,76,57.816892,25,21,20,6,11,15,14,8
1,92,92,79000000.0,375000.0,29,185,80,53.0,1.0,243.0,...,85,57.816892,22,31,23,7,11,15,14,11
2,90,90,54500000.0,275000.0,30,180,80,19.0,1.0,21.0,...,80,57.816892,29,26,26,10,8,11,5,15
3,90,90,52500000.0,275000.0,32,195,95,16.0,1.0,73.0,...,91,57.816892,25,41,27,13,15,10,9,12
4,90,90,63500000.0,300000.0,28,193,92,19.0,1.0,21.0,...,37,57.816892,25,25,25,87,85,92,90,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46,61,110000.0,700.0,18,180,73,2012.0,1.0,112978.0,...,54,40.000000,23,21,25,9,13,13,12,7
161579,46,58,110000.0,750.0,19,188,83,2012.0,1.0,112429.0,...,31,35.000000,50,51,45,6,14,8,13,14
161580,46,58,110000.0,500.0,19,181,73,65.0,1.0,563.0,...,37,35.000000,36,45,50,8,9,7,14,9
161581,46,70,150000.0,500.0,17,175,68,65.0,1.0,306.0,...,63,43.000000,19,17,14,13,12,14,7,13
161582,46,63,110000.0,500.0,17,180,70,350.0,1.0,112990.0,...,25,30.000000,50,45,42,13,7,6,6,14

In [14]:
non_numeric

,player_positions,league_name,club_name,club_position,nationality_name,preferred_foot,work_rate,body_type,real_face,ls,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,CF,La Liga,FC Barcelona,CF,Argentina,Left,Medium/Low,Normal (170-),Yes,89+3,...,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3
1,"LW, LM",La Liga,Real Madrid CF,LW,Portugal,Right,High/Low,Normal (185+),Yes,91+1,...,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3
2,"RM, LM, RW",Bundesliga,FC Bayern München,SUB,Netherlands,Left,High/Low,Normal (170-185),Yes,84+3,...,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3
3,ST,Ligue 1,Paris Saint-Germain,ST,Sweden,Right,Medium/Low,Normal (185+),Yes,87+3,...,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3
4,GK,Bundesliga,FC Bayern München,GK,Germany,Right,Medium/Medium,Normal (185+),Yes,38+3,...,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,RW,Super League,Hebei CFFC,RES,China PR,Right,Medium/Medium,Lean (170-185),No,47+2,...,32+2,32+2,32+2,37+2,36+2,31+2,31+2,31+2,36+2,14+2
161579,LB,Super League,Guangzhou R&F,RES,China PR,Left,Medium/Medium,Normal (185+),No,35+2,...,41+2,41+2,41+2,43+2,44+2,48+2,48+2,48+2,44+2,15+2
161580,CDM,Premier Division,Sligo Rovers,RES,Republic of Ireland,Right,High/Medium,Normal (170-185),No,46+2,...,45+2,45+2,45+2,47+2,47+2,46+2,46+2,46+2,47+2,14+2
161581,"RW, LW",Premier Division,Shamrock Rovers,RES,Republic of Ireland,Right,Medium/Medium,Normal (170-185),No,47+2,...,30+2,30+2,30+2,34+2,32+2,28+2,28+2,28+2,32+2,15+2
161582,CB,Pro League,Al Batin,RES,Saudi Arabia,Right,Medium/Medium,Lean (170-185),No,32+2,...,40+2,40+2,40+2,39+2,41+2,46+2,46+2,46+2,41+2,13+2

In [15]:
cat_impt=pd.get_dummies(non_numeric).astype(int)

In [16]:
cat_impt

,player_positions_CAM,"player_positions_CAM, CDM","player_positions_CAM, CDM, CB","player_positions_CAM, CDM, CF","player_positions_CAM, CDM, CM","player_positions_CAM, CDM, CM, CB","player_positions_CAM, CDM, CM, CF","player_positions_CAM, CDM, CM, LM","player_positions_CAM, CDM, CM, RM","player_positions_CAM, CDM, CM, RW",...,gk_87+3,gk_88+2,gk_88+3,gk_89+2,gk_89+3,gk_9,gk_9+1,gk_9+2,gk_9+3,gk_90+2
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
161579,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
161580,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
161581,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
161582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

FINDING THE CORRELATION FOR THE VARIABLES WITH RATINGS

In [17]:
corr_matrix = number_impt.corr()

# Getting the correlation values with the 'overall' column
overall_corr = corr_matrix['overall']

# Sorting the correlations
sorted_correlations = overall_corr.abs().sort_values(ascending=False)

# taking  the top 15 columns (excluding 'overall' itself)
top_15_features = sorted_correlations.index[1:16]
new_df = number_impt[top_15_features]

In [18]:
new_df

,movement_reactions,potential,passing,wage_eur,mentality_composure,value_eur,dribbling,attacking_short_passing,mentality_vision,international_reputation,skill_long_passing,power_shot_power,physic,age,skill_ball_control
0,94,95,86.000000,550000.0,57.816892,100500000.0,96.000000,89,90,5,76,80,63.000000,27,96
1,90,92,81.000000,375000.0,57.816892,79000000.0,91.000000,82,81,5,72,94,79.000000,29,92
2,89,90,83.000000,275000.0,57.816892,54500000.0,92.000000,86,84,5,76,86,64.000000,30,90
3,85,90,81.000000,275000.0,57.816892,52500000.0,86.000000,84,83,5,76,93,86.000000,32,90
4,89,90,56.938175,300000.0,57.816892,63500000.0,62.081872,42,20,5,41,42,64.814364,28,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,39,61,40.000000,700.0,40.000000,110000.0,47.000000,38,42,1,33,64,44.000000,18,45
161579,42,58,29.000000,750.0,35.000000,110000.0,34.000000,30,31,1,25,33,57.000000,19,32
161580,50,58,43.000000,500.0,35.000000,110000.0,46.000000,51,40,1,43,51,53.000000,19,35
161581,45,70,36.000000,500.0,43.000000,150000.0,46.000000,40,44,1,26,42,42.000000,17,43
161582,40,63,26.000000,500.0,30.000000,110000.0,32.000000,32,20,1,29,33,57.000000,17,31

In [19]:
main_df = new_df.drop(columns = ['wage_eur','value_eur','international_reputation'],inplace = False)

In [20]:
main_df

,movement_reactions,potential,passing,mentality_composure,dribbling,attacking_short_passing,mentality_vision,skill_long_passing,power_shot_power,physic,age,skill_ball_control
0,94,95,86.000000,57.816892,96.000000,89,90,76,80,63.000000,27,96
1,90,92,81.000000,57.816892,91.000000,82,81,72,94,79.000000,29,92
2,89,90,83.000000,57.816892,92.000000,86,84,76,86,64.000000,30,90
3,85,90,81.000000,57.816892,86.000000,84,83,76,93,86.000000,32,90
4,89,90,56.938175,57.816892,62.081872,42,20,41,42,64.814364,28,31
...,...,...,...,...,...,...,...,...,...,...,...,...
161578,39,61,40.000000,40.000000,47.000000,38,42,33,64,44.000000,18,45
161579,42,58,29.000000,35.000000,34.000000,30,31,25,33,57.000000,19,32
161580,50,58,43.000000,35.000000,46.000000,51,40,43,51,53.000000,19,35
161581,45,70,36.000000,43.000000,46.000000,40,44,26,42,42.000000,17,43
161582,40,63,26.000000,30.000000,32.000000,32,20,29,33,57.000000,17,31

TRAINING MY DATASETS

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
X = main_df
scaler=StandardScaler()
X=scaler.fit_transform(X)
y =number_impt['overall']

In [22]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import pickle

Using MSE to check the best model

In [24]:
models = {
    'GradientBoosting': GradientBoostingRegressor(),
    'LinearRegression': LinearRegression(),
    'DecisionTree': DecisionTreeRegressor()
}

# Dictionary to hold MSE values
mse_scores = {}

# Train each model and evaluate performance
for name, model in models.items():
    model.fit(Xtrain, Ytrain)
    y_pred = model.predict(Xtest)
    mse = mean_squared_error(Ytest, y_pred)
    mse_scores[name] = mse

    print(f"{name} MSE: {mse}")

GradientBoosting MSE: 2.0843140622947693
LinearRegression MSE: 4.302781399072637
DecisionTree MSE: 3.282390073336015

Using Cross Validation Score to check the best

In [26]:
##For LinearRegression
from sklearn.model_selection import cross_val_score
model = LinearRegression()
num_folds = 10

## cross-validation scores
cv_scores = cross_val_score(model, X, y, cv=num_folds, scoring='neg_mean_squared_error')
print("Cross-validation scores:", cv_scores)
print(f"Mean CV score: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

Cross-validation scores: [-4.68496936 -3.84029698 -4.69714668 -4.38363376 -4.15452255 -4.24694529
 -4.50499503 -4.69898039 -4.29693493 -4.04277418]
Mean CV score: -4.3551 (+/- 0.2802)

In [27]:
##fOR DecisonTree regression
model = DecisionTreeRegressor()
num_folds = 10

# Compute cross-validation scores
cv_scores = cross_val_score(model, X, y, cv=num_folds, scoring='neg_mean_squared_error')
print("Cross-validation scores:", cv_scores)
print(f"Mean CV score: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

Cross-validation scores: [-4.48672566 -3.68314871 -3.54081317 -3.02104221 -3.06702562 -2.95222181
 -3.24514173 -3.3202129  -3.23895284 -3.29564303]
Mean CV score: -3.3851 (+/- 0.4244)

In [28]:
##For GrdientBoosting 
model = GradientBoostingRegressor()
num_folds = 10

# Compute cross-validation scores
cv_scores = cross_val_score(model, X, y, cv=num_folds, scoring='neg_mean_squared_error')
print("Cross-validation scores:", cv_scores)
print(f"Mean CV score: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

Cross-validation scores: [-2.86517469 -2.18347258 -2.49554992 -2.02147207 -1.87816207 -1.83393683
 -2.06201761 -2.30910562 -2.02423784 -1.91532551]
Mean CV score: -2.1588 (+/- 0.3042)

In [32]:
from sklearn.datasets import make_regression
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import mean_squared_error, r2_score

X, y = make_regression(n_samples=100, n_features=10, noise=0.1, random_state=42)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Function to perform grid search
def perform_grid_search(model, param_grid, X_train, y_train):
    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, 
                               cv=5, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
    grid_search.fit(X_train, y_train)
    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    return best_model, best_params, best_score

# Linear Regression
linear_model = LinearRegression()
linear_param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [None, 1, 2, 4, 8]
}
best_linear_model, best_linear_params, best_linear_score = perform_grid_search(linear_model, linear_param_grid, X_train, y_train)

print(f"Best Linear Regression parameters: {best_linear_params}")
print(f"Best Linear Regression cross-validation score: {best_linear_score}")

# Decision Tree Regressor
tree_model = DecisionTreeRegressor()
tree_param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
best_tree_model, best_tree_params, best_tree_score = perform_grid_search(tree_model, tree_param_grid, X_train, y_train)

print(f"Best Decision Tree Regressor parameters: {best_tree_params}")
print(f"Best Decision Tree Regressor cross-validation score: {best_tree_score}")

# Gradient Boosting Regressor
gbr_model = GradientBoostingRegressor()
gbr_param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}
best_gbr_model, best_gbr_params, best_gbr_score = perform_grid_search(gbr_model, gbr_param_grid, X_train, y_train)

print(f"Best Gradient Boosting Regressor parameters: {best_gbr_params}")
print(f"Best Gradient Boosting Regressor cross-validation score: {best_gbr_score}")

# Evaluate the best models on test data
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, r2

linear_mse, linear_r2 = evaluate_model(best_linear_model, X_test, y_test)
tree_mse, tree_r2 = evaluate_model(best_tree_model, X_test, y_test)
gbr_mse, gbr_r2 = evaluate_model(best_gbr_model, X_test, y_test)

print(f"Linear Regression Test MSE: {linear_mse}, R-squared: {linear_r2}")
print(f"Decision Tree Regressor Test MSE: {tree_mse}, R-squared: {tree_r2}")
print(f"Gradient Boosting Regressor Test MSE: {gbr_mse}, R-squared: {gbr_r2}")

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best Linear Regression parameters: {'copy_X': True, 'fit_intercept': True, 'n_jobs': None}
Best Linear Regression cross-validation score: -0.013271002812042399
Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Decision Tree Regressor parameters: {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 10}
Best Decision Tree Regressor cross-validation score: -13787.797127495936
Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best Gradient Boosting Regressor parameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
Best Gradient Boosting Regressor cross-validation score: -8725.03190848665
Linear Regression Test MSE: 0.010265673458310596, R-squared: 0.9999998282331861
Decision Tree Regressor Test MSE: 30396.292393240023, R-squared: 0.4914045999344857
Gradient Boosting Regressor Test MSE: 16793.689455112726, R-squared: 0.7190054268296688

From the above data, the best performing data model is the Linear Regression Model which has R square of 0.9999 the best of them all

In [60]:
best_model2 = GradientBoostingRegressor(learning_rate=0.1, max_depth=3, n_estimators=200)

In [61]:

# Save the model to a file using pickle
with open('best_model2.pkl', 'wb') as file:
    pickle.dump(best_model2, file)

TESTING THE MODEL

In [34]:
test = pd.read_csv('players_22.csv')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12224\1082073338.py:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  test = pd.read_csv('players_22.csv')

In [35]:
test

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,https://sofifa.com/player/261962/defu-song/220002,Song Defu,宋德福,CDM,47,52,70000.0,1000.0,22,...,46+2,46+2,46+2,48+2,15+2,https://cdn.sofifa.net/players/261/962/22_120.png,https://cdn.sofifa.net/teams/112541/60.png,https://cdn.sofifa.net/flags/cn.png,NaN,https://cdn.sofifa.net/flags/cn.png
19235,262040,https://sofifa.com/player/262040/caoimhin-port...,C. Porter,Caoimhin Porter,CM,47,59,110000.0,500.0,19,...,44+2,44+2,44+2,48+2,14+2,https://cdn.sofifa.net/players/262/040/22_120.png,https://cdn.sofifa.net/teams/445/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19236,262760,https://sofifa.com/player/262760/nathan-logue/...,N. Logue,Nathan Logue-Cunningham,CM,47,55,100000.0,500.0,21,...,45+2,45+2,45+2,47+2,12+2,https://cdn.sofifa.net/players/262/760/22_120.png,https://cdn.sofifa.net/teams/111131/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19237,262820,https://sofifa.com/player/262820/luke-rudden/2...,L. Rudden,Luke Rudden,ST,47,60,110000.0,500.0,19,...,26+2,26+2,26+2,32+2,15+2,https://cdn.sofifa.net/players/262/820/22_120.png,https://cdn.sofifa.net/teams/111131/60.png,https://cdn.sofifa.net/flags/ie.png,NaN,https://cdn.sofifa.net/flags/ie.png
19238,264540,https://sofifa.com/player/264540/emanuel-lalch...,E. Lalchhanchhuaha,Emanuel Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,...,41+2,41+2,41+2,45+2,16+2,https://cdn.sofifa.net/players/264/540/22_120.png,https://cdn.sofifa.net/teams/113040/60.png,https://cdn.sofifa.net/flags/in.png,NaN,https://cdn.sofifa.net/flags/in.png

In [36]:
test.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name',
       'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur',
       'age',
       ...
       'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url',
       'club_flag_url', 'nation_logo_url', 'nation_flag_url'],
      dtype='object', length=110)

In [37]:
test = test.drop(columns = ['player_url','short_name','long_name','player_face_url','club_logo_url','nation_flag_url','club_flag_url','nation_logo_url'],inplace=False)

In [38]:
test

,sofifa_id,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,158023,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,170,72,...,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3
1,188545,ST,92,92,119500000.0,270000.0,32,1988-08-21,185,81,...,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
2,20801,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,187,83,...,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3
3,190871,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,175,68,...,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3
4,192985,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,181,70,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,CDM,47,52,70000.0,1000.0,22,1999-01-02,180,64,...,46+2,46+2,46+2,48+2,48+2,46+2,46+2,46+2,48+2,15+2
19235,262040,CM,47,59,110000.0,500.0,19,2002-03-18,175,70,...,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2
19236,262760,CM,47,55,100000.0,500.0,21,2000-02-07,178,72,...,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2
19237,262820,ST,47,60,110000.0,500.0,19,2002-04-23,173,66,...,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2
19238,264540,CAM,47,60,110000.0,500.0,19,2002-02-06,167,61,...,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2

In [39]:
threshold = 0.3 * len(test)

# Identify columns to drop
columns_to_drop = []
for col in test.columns:
    if test[col].isna().sum() > threshold:
        columns_to_drop.append(col)

# Drop the columns
test.drop(columns=columns_to_drop, inplace=True)

test_main = test

In [40]:
test_main

,sofifa_id,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,158023,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,170,72,...,64+3,64+3,64+3,66+3,61+3,50+3,50+3,50+3,61+3,19+3
1,188545,ST,92,92,119500000.0,270000.0,32,1988-08-21,185,81,...,66+3,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
2,20801,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,187,83,...,59+3,59+3,59+3,63+3,60+3,53+3,53+3,53+3,60+3,20+3
3,190871,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,175,68,...,63+3,63+3,63+3,67+3,62+3,50+3,50+3,50+3,62+3,20+3
4,192985,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,181,70,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,CDM,47,52,70000.0,1000.0,22,1999-01-02,180,64,...,46+2,46+2,46+2,48+2,48+2,46+2,46+2,46+2,48+2,15+2
19235,262040,CM,47,59,110000.0,500.0,19,2002-03-18,175,70,...,46+2,46+2,46+2,49+2,48+2,44+2,44+2,44+2,48+2,14+2
19236,262760,CM,47,55,100000.0,500.0,21,2000-02-07,178,72,...,46+2,46+2,46+2,47+2,47+2,45+2,45+2,45+2,47+2,12+2
19237,262820,ST,47,60,110000.0,500.0,19,2002-04-23,173,66,...,29+2,29+2,29+2,33+2,32+2,26+2,26+2,26+2,32+2,15+2
19238,264540,CAM,47,60,110000.0,500.0,19,2002-02-06,167,61,...,44+2,44+2,44+2,45+2,45+2,41+2,41+2,41+2,45+2,16+2

In [41]:
num_data=test_main.select_dtypes(include=np.number)

In [42]:
num_impt= num_data.fillna(num_data.mean())

In [43]:
num_impt

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,158023,93,93,78000000.0,320000.0,34,170,72,73.0,1.0,...,75,96,20,35,24,6,11,15,14,8
1,188545,92,92,119500000.0,270000.0,32,185,81,21.0,1.0,...,90,88,35,42,19,15,6,12,8,10
2,20801,91,91,45000000.0,270000.0,36,187,83,11.0,1.0,...,88,95,24,32,24,7,11,15,14,11
3,190871,91,91,129000000.0,270000.0,29,175,68,73.0,1.0,...,93,93,35,32,29,9,9,15,15,11
4,192985,91,91,125500000.0,350000.0,30,181,70,10.0,1.0,...,83,89,68,65,53,15,13,5,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,47,52,70000.0,1000.0,22,180,64,112541.0,1.0,...,42,37,38,43,48,6,10,5,15,13
19235,262040,47,59,110000.0,500.0,19,175,70,445.0,1.0,...,44,47,37,44,47,11,12,6,8,10
19236,262760,47,55,100000.0,500.0,21,178,72,111131.0,1.0,...,39,36,38,44,48,8,6,7,10,6
19237,262820,47,60,110000.0,500.0,19,173,66,111131.0,1.0,...,49,47,10,14,11,7,10,7,14,15
19238,264540,47,60,110000.0,500.0,19,167,61,113040.0,1.0,...,35,36,33,31,37,8,13,13,9,14

In [44]:
corr_matrix = num_impt.corr()

# Getting the correlation values with the 'overall' column
overall_corr = corr_matrix['overall']

# Sorting the correlations
sorted_correlations = overall_corr.abs().sort_values(ascending=False)

# taking  the top 15 columns (excluding 'overall' itself)
top_10_features = sorted_correlations.index[1:12]
test_df = num_impt[top_10_features]

In [45]:
test_df

,movement_reactions,mentality_composure,passing,potential,dribbling,wage_eur,power_shot_power,value_eur,release_clause_eur,mentality_vision,attacking_short_passing
0,94,96,91.0,93,95.0,320000.0,86,78000000.0,144300000.0,95,91
1,93,88,79.0,92,86.0,270000.0,90,119500000.0,197200000.0,81,85
2,94,95,80.0,91,88.0,270000.0,94,45000000.0,83300000.0,76,80
3,89,93,86.0,91,94.0,270000.0,80,129000000.0,238700000.0,90,86
4,91,89,93.0,91,88.0,350000.0,91,125500000.0,232200000.0,94,94
...,...,...,...,...,...,...,...,...,...,...,...
19234,53,37,46.0,52,48.0,1000.0,46,70000.0,114000.0,43,50
19235,49,47,50.0,59,46.0,500.0,49,110000.0,193000.0,49,51
19236,46,36,45.0,55,49.0,500.0,50,100000.0,175000.0,46,49
19237,48,47,36.0,60,48.0,500.0,48,110000.0,239000.0,40,38
19238,54,36,45.0,60,48.0,500.0,50,110000.0,217000.0,46,50

In [46]:
test_df = test_df.drop(columns = ['wage_eur','value_eur','release_clause_eur'],inplace = False)

In [47]:
test_df

,movement_reactions,mentality_composure,passing,potential,dribbling,power_shot_power,mentality_vision,attacking_short_passing
0,94,96,91.0,93,95.0,86,95,91
1,93,88,79.0,92,86.0,90,81,85
2,94,95,80.0,91,88.0,94,76,80
3,89,93,86.0,91,94.0,80,90,86
4,91,89,93.0,91,88.0,91,94,94
...,...,...,...,...,...,...,...,...
19234,53,37,46.0,52,48.0,46,43,50
19235,49,47,50.0,59,46.0,49,49,51
19236,46,36,45.0,55,49.0,50,46,49
19237,48,47,36.0,60,48.0,48,40,38
19238,54,36,45.0,60,48.0,50,46,50

In [48]:
X_22 = test_df

In [49]:
y_22 = num_impt['overall']

In [50]:
best_model.fit(X_22, y_22)

# Make predictions on the new dataset
y_pred_22 = best_model.predict(X_22)
# Calculate performance metrics
mse_players_22 = mean_squared_error(y_22, y_pred_22)
r2_players_22 = r2_score(y_22, y_pred_22)

print(f"MSE on players_22 dataset: {mse_players_22}")
print(f"R-squared on players_22 dataset: {r2_players_22}")

MSE on players_22 dataset: 6.899889391741205
R-squared on players_22 dataset: 0.8542332067548233

The R-squared performance that is shown here shows that my model has an 85% accuracy rate meaning it is a fairly strong model.

In [51]:
import streamlit as st

In [62]:
best_model.fit(X_22, y_22)

# Streamlit app
st.title("Player Rating Prediction")

# Collect user input features
st.sidebar.header('User Input Features')

def user_input_features():
    # Collect feature inputs from the user
    feature1 = st.sidebar.number_input("Feature 1")
    feature2 = st.sidebar.number_input("Feature 2")
    # Add more feature inputs as needed
    data = {'feature1': feature1, 'feature2': feature2}  # Adjust keys as per your feature names
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()

# Display user input features
st.subheader('User Input Features')
st.write(input_df)

# Preprocessing  user input
input_df_processed = pd.get_dummies(input_df)
# Ensure the input data matches the model's expected features
input_df_processed = input_df_processed.reindex(columns=X_22.columns, fill_value=0)

# Predict and display the results
prediction = best_model.predict(input_df_processed)
st.subheader('Prediction')
st.write(prediction[0])